# Generated by Django 3.0.5 on 2020-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200416_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
