# Generated by Django 4.0.3 on 2022-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of product')),
                ('price', models.FloatField(verbose_name='Price of product')),
                ('description', models.TextField(verbose_name='Description of product')),
                ('count', models.IntegerField(verbose_name='Count of product')),
                ('is_active', models.BooleanField(verbose_name='Sign of activity of a product')),
            ],
        ),
    ]
